apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vitals-ingress
  namespace: vitals-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: vitals.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vitals-frontend-service
            port:
              number: 3000
  - host: vitals-backend-service
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vitals-backend-service
            port:
              number: 8080
