prometheus:
  prometheusSpec:
    retention: 2h
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 150Mi

grafana:
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 500Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 30Mi
    limits:
      cpu: 50m
      memory: 50Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 30Mi
    limits:
      cpu: 50m
      memory: 60Mi
